export const ENRICHMENT_CONFIG = {
  CONCURRENCY_PER_USER: 3,
  MAX_RETRY_ATTEMPTS: 3,
  BATCH_SIZE: 50,
  STALE_THRESHOLD_MS: 15 * 24 * 60 * 60 * 1000,

  RAPIDAPI_RATE_LIMIT_PER_SEC: 5,
  RAPIDAPI_DAILY_CAP: 10_000,
  RAPIDAPI_BASE_DELAY_MS: 1000,
  RAPIDAPI_MAX_DELAY_MS: 60_000,
  RAPIDAPI_BACKOFF_FACTOR: 2,

  EMBEDDING_MODEL: 'local-hash-v1',
  EMBEDDING_DIMENSIONS: 1536,
  EMBEDDING_VERSION: 'openai-v1',
  EMBEDDING_BATCH_SIZE: 100,

  VECTOR_INDEX_NAME: 'follower_vector_index',
  VECTOR_NUM_CANDIDATES: 200,
  VECTOR_DEFAULT_K: 100,

  JOB_LOCK_TTL_MS: 10 * 60 * 1000,
  JOB_HEARTBEAT_MS: 2 * 60 * 1000,

  DEAD_LETTER_THRESHOLD: 5,

  SEARCH_DEFAULT_LIMIT: 20,
  SEARCH_MAX_LIMIT: 100,

  RERANK_WEIGHTS: {
    semantic: 0.60,
    reputation: 0.25,
    recency: 0.10,
    intent: 0.05,
  },
};
